# Generated by Django 5.2 on 2025-04-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projects_user_alter_projects_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
